src/Buzmarev/QueueManagerBundle/Entity/Queue.php
<?php

namespace App\Buzmarev\QueueManagerBundle\Entity;

use App\Buzmarev\QueueManagerBundle\Repository\QueueRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QueueRepository::class)
 */
class Queue
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Status::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $status_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $task_class;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $start_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatusId(): ?Status
    {
        return $this->status_id;
    }

    public function setStatusId(?Status $status_id): self
    {
        $this->status_id = $status_id;

        return $this;
    }

    public function getTaskClass(): ?string
    {
        return $this->task_class;
    }
    
    public function getTaskName(): ?string
    {
        return $this->task_class::taskName;
    }

    public function setTaskClass(string $task_class): self
    {
        $this->task_class = $task_class;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getStartAt(): ?\DateTimeInterface
    {
        return $this->start_at;
    }

    public function setStartAt(?\DateTimeInterface $start_at): self
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getEndAt(): ?\DateTimeInterface
    {
        return $this->end_at;
    }

    public function setEndAt(?\DateTimeInterface $end_at): self
    {
        $this->end_at = $end_at;

        return $this;
    }
}

src/Buzmarev/QueueManagerBundle/Entity/Status.php
<?php

namespace App\Buzmarev\QueueManagerBundle\Entity;

use App\Buzmarev\QueueManagerBundle\Repository\StatusRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StatusRepository::class)
 */
class Status
{
    public const PENDING = 1;
    public const SUCCESS = 2;
    public const FAILED = 3;
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Buzmarev/QueueManagerBundle/Controller/QueueController.php
<?php

namespace App\Buzmarev\QueueManagerBundle\Controller;

use App\Buzmarev\QueueManagerBundle\Entity\Status;
use App\Buzmarev\QueueManagerBundle\Entity\Queue;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class QueueController extends AbstractController
{
    public function index(Request $request, ManagerRegistry $doctrine): Response
    {
        $statuses = $doctrine->getRepository(Status::class)->findAll();
        $queues = $doctrine->getRepository(Queue::class)->findBy(
            [
                'status_id' => $request->request->get('filter')
            ]
        );
        return $this->render('@QueueManager/queue.html.twig', [
            'statuses' => $statuses,
            'queues' => $queues
        ]);
    }
}

src/Buzmarev/QueueManagerBundle/Controller/QueueManagerController.php
<?php

namespace App\Buzmarev\QueueManagerBundle\Controller;

use App\Buzmarev\QueueManagerBundle\Tasks\Task\Task1;
use App\Buzmarev\QueueManagerBundle\Tasks\Task\Task2;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class QueueManagerController extends AbstractController
{
    public function index(): Response
    {
        return $this->render('@QueueManager/index.html.twig', [
            'task_name_1' => Task1::taskName,
            'task_name_2' => Task2::taskName
        ]);
    }
}

src/Buzmarev/QueueManagerBundle/Controller/Task1Controller.php
<?php

namespace App\Buzmarev\QueueManagerBundle\Controller;

use App\Buzmarev\QueueManagerBundle\Entity\Status;
use App\Buzmarev\QueueManagerBundle\Entity\Queue;
use App\Buzmarev\QueueManagerBundle\Tasks\Task\Task1;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class Task1Controller extends AbstractController
{
    public function index(): Response
    {
        return $this->render('@QueueManager/task_1.html.twig', [
            'task_name' => Task1::taskName
        ]);
    }
    
    public function launch(Request $request, ManagerRegistry $doctrine): Response
    {
        $qnt = $request->request->get('qnt');
        
        $entityManager = $doctrine->getManager();
        $status = $doctrine->getRepository(Status::class)->find(Status::PENDING);

        for ($i=0; $i < $qnt; $i++) {
            $queue = new Queue();
            $queue->setStatusId($status);
            $queue->setTaskClass(Task1::class);
            $queue->setCreatedAt(new \DateTimeImmutable('now'));

            $entityManager->persist($queue);
        }
        $entityManager->flush();
        
        return $this->redirectToRoute(
            'task_1_page',
            [
                'task_name' => Task1::taskName
            ]
        );
    }
}

src/Buzmarev/QueueManagerBundle/Controller/Task2Controller.php
<?php

namespace App\Buzmarev\QueueManagerBundle\Controller;

use App\Buzmarev\QueueManagerBundle\Entity\Status;
use App\Buzmarev\QueueManagerBundle\Entity\Queue;
use App\Buzmarev\QueueManagerBundle\Tasks\Task\Task2;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class Task2Controller extends AbstractController
{
    public function index(): Response
    {
        return $this->render('@QueueManager/task_2.html.twig', [
            'task_name' => Task2::taskName
        ]);
    }
    
    public function launch(Request $request, ManagerRegistry $doctrine): Response
    {
        $qnt = $request->request->get('qnt');
        
        $entityManager = $doctrine->getManager();
        $status = $doctrine->getRepository(Status::class)->find(Status::PENDING);

        for ($i=0; $i < $qnt; $i++) {
            $queue = new Queue();
            $queue->setStatusId($status);
            $queue->setTaskClass(Task2::class);
            $queue->setCreatedAt(new \DateTimeImmutable('now'));

            $entityManager->persist($queue);
        }
        $entityManager->flush();
        
        return $this->redirectToRoute(
            'task_2_page',
            [
                'task_name' => Task2::taskName
            ]
        );
    }
}

src/Buzmarev/QueueManagerBundle/templates/index.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Welcome!</title>
    </head>
    <body>
        <h1>Queue Manager</h1>
        <a href="{{ path('queue_page') }}">Очереди</a>
        <a href="{{ path('task_1_page') }}">{{ task_name_1 }}</a>
        <a href="{{ path('task_2_page') }}">{{ task_name_2 }}</a>
    </body>
</html>

src/Buzmarev/QueueManagerBundle/templates/queue.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Welcome!</title>
    </head>
    <body>
        <h1>Очереди</h1>
        <a href="{{ path('index_page') }}">Queue Manager</a>
        <br>
        <br>
        <div>
            <form method="POST">
                {% for status in statuses %}
                    <div>
                        <input type="radio" name="filter" value="{{ status.id }}">
                        <label>{{ status.name }}</label>
                    </div>
                {% endfor %}
                <button type='submit'>Обновить</button> 
            </form>
            
            <table border="1">
                <caption>Очередь</caption>
                <tr>
                    <th>Название Таски</th>
                    <th>Статус</th>
                    <th>Дата создания</th>
                    <th>Дата запуска</th>
                    <th>Дата завершения</th>
                </tr>
                {% for queue in queues %}
                    <tr>
                        <td>{{ queue.taskName }}</td>
                        <td>{{ queue.statusId.name }}</td>
                        <td>{{ queue.createdAt|date('Y-m-d H:i:s') }}</td>
                        <td>{{ queue.startAt|date('Y-m-d H:i:s') }}</td>
                        <td>{{ queue.endAt|date('Y-m-d H:i:s') }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </body>
</html>

src/Buzmarev/QueueManagerBundle/templates/task_1.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Welcome!</title>
    </head>
    <body>
        <h1>{{ task_name }}</h1>
        <a href="{{ path('index_page') }}">Queue Manager</a>
        <div>
            <p><b>Поставить в очередь</b></p>
            <form action="{{ path('task_1_launch') }}" method="POST">
                <p>Количество задач</p>
                <input name="qnt" type="number" min="1" max="100" value="1">
                <br>
                <br>
                <button type='submit'>Отправить {{ task_name }} в работу</button>
            </form>
        </div>
    </body>
</html>

src/Buzmarev/QueueManagerBundle/templates/task_2.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Welcome!</title>
    </head>
    <body>
        <h1>{{ task_name }}</h1>
        <a href="{{ path('index_page') }}">Queue Manager</a>
        <div>
            <p><b>Поставить в очередь</b></p>
            <form action="{{ path('task_2_launch') }}" method="POST">
                <p>Количество задач</p>
                <input name="qnt" type="number" min="1" max="100" value="1">
                <br>
                <br>
                <button type='submit'>Отправить {{ task_name }} в работу</button>
            </form>
        </div>
    </body>
</html>